#include "leak_update_tc2.h"
#include <stdint.h>
#include "plib_tc2.h"

volatile bool leakdet_tick = false;

static volatile uint32_t isr_hz = 0;   // TC2 interrupt rate (Hz)
static volatile uint32_t fout_hz = 5;  // desired detector rate (Hz)
static volatile uint32_t acc = 0;      // fractional divider accumulator

static void tc2_cb(TC_TIMER_STATUS status, uintptr_t context) {
    (void)context;
    if ((status & TC_INTFLAG_OVF_Msk) == 0U)
        return;

    // Fractional divide using an integer NCO:
    // Every ISR, add fout; when accumulator crosses isr_hz, emit one 5 Hz tick.
    acc += fout_hz;
    if (acc >= isr_hz) {
        acc -= isr_hz;
        leakdet_tick = true;
    }
}

void timing_tc2_init_5hz(void) {
    // Use TC2 exactly as generated by MHC/PLIB
    TC2_TimerInitialize();
    TC2_TimerCallbackRegister(tc2_cb, 0);

    // Compute actual ISR frequency from PLIB settings (no PLIB edits needed)
    const uint32_t tc_clk_hz = TC2_TimerFrequencyGet();  // 48_000_000
    const uint32_t period =
        (uint32_t)TC2_Timer16bitPeriodGet() + 1U;  // 47999+1
    // Prescaler is DIV1 in your PLIB, so:
    isr_hz = tc_clk_hz / period;  // ~1000 Hz
    if (isr_hz == 0U)
        isr_hz = 1000U;  // fallback

    acc = 0;
    TC2_TimerStart();
}
