#include <same51j20a.h>
#include "supc.h"
#include "../port/port.h"

/* Handler for interrupts generated by crossing BOD threshold*/
void __attribute__((used)) SUPC_BODDET_Handler(void) {
    LED0_Toggle();
    SUPC_REGS->SUPC_INTFLAG |= SUPC_INTFLAG_BOD33DET_Msk;
    return;
}


