#include  <samc21e17a.h>
#include "supc.h"
#include <stdint.h>
#include <component/supc.h>

volatile int8_t bod33_crossed = 0;

void SUPC_Initialize(void) {
    SUPC_REGS->SUPC_INTENSET = SUPC_INTENSET_BODVDDDET_Msk;
    return;
}

/* 
 * Handler for interrupts generated by crossing BOD33 threshold 
 * Toggles 
 */
void __attribute__((used)) SUPC_BODDET_Handler(void) {
    if ((SUPC_REGS->SUPC_STATUS & SUPC_STATUS_BODVDDDET_Msk) != SUPC_STATUS_BODVDDDET_Msk) {
        bod33_crossed = 1;
        SUPC_REGS->SUPC_INTFLAG = SUPC_INTFLAG_BODVDDDET_Msk;
    }
}



